#!/bin/bash

module load openjdk/11.0.5-10
#module load jdk/11.0.4

RefFa=/rsrch3/scratch/reflib/iacs/reference/human/hg19/fastas/Homo_sapiens_assembly19.fasta
TimeID=$(date +%Y%m%d%H%M%S)

JavaOption='--java-options "-Xmx40G"'

#$1:BamList
#$2:StoreDir

BamList=$1
StoreDir=$2

InputBamConcatPath=$(cat ${BamList} | xargs -i printf "-I "{}" ")

CH_List="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y"


################
# GATK 4.2.0.0 #
################

GATKver="gatk4200"
#GnomadVCF=/rsrch3/home/leuk-rsrch/huryu/Database/hg19/GnomadDataForMutect/af-only-gnomad.raw.sites.h19.vcf
PON_PANEL_DIR="/rsrch3/scratch/leuk-rsrch/huryu/Lab_bamFile/Mutect_Line/PON_BuiltWithoutgNomad/MutectPONCreate/PON_PANEL/"
#StoreDir=MutectCall_result_WithoutGivenGnomad_gatk4200/${Tag}/

mkdir -p ${StoreDir}

for CH in ${CH_List}
do
  CHR=chr${CH}
  PON_VCF=${PON_PANEL_DIR}/"pon_${CHR}.vcf.gz"
  mkdir -p ${StoreDir}/${CHR}/

  bsub -W 240:00 -q long -n 20 -M 40G -R rusage[mem=40] -e ${StoreDir}/MutectCall_err.log -o ${StoreDir}/MutectCall_out.log \
       -J "MutectCall_${CH}_${TimeID}" \
       "${GATKver} ${JavaOption} \
        Mutect2 -R ${RefFa} -L ${CH} ${InputBamConcatPath} -pon ${PON_VCF} \
                --f1r2-tar-gz ${StoreDir}/${CHR}/${CHR}.f1r2.tar.gz \
                -O ${StoreDir}/${CHR}/${CHR}.unfiltered.vcf"
done


all_UnFilvcf=$(printf "${CH_List}" | xargs -d " " -i printf "-I ${StoreDir}/chr"{}"/chr"{}".unfiltered.vcf ")
all_UnFilvcfStats=$(printf "${CH_List}" | xargs -d " " -i printf "-stats ${StoreDir}/chr"{}"/chr"{}".unfiltered.vcf.stats ")
all_f1r2_input=$(printf "${CH_List}" | xargs -d " " -i printf "-I ${StoreDir}/chr"{}"/chr"{}".f1r2.tar.gz ")

#all_UnFilvcf=$(for CH in ${CH_List}; do   CHR=chr${CH};   printf -- "-I ${StoreDir}/${CHR}/${Tag}.${CHR}.unfiltered.vcf "; done)
#all_UnFilvcfStats=$(for CH in ${CH_List}; do   CHR=chr${CH};   printf -- "-stats ${StoreDir}/${CHR}/${Tag}.${CHR}.unfiltered.vcf.stats "; done)
#all_f1r2_input=$(for CH in ${CH_List}; do   CHR=chr${CH};   printf -- "-I ${StoreDir}/${CHR}/${Tag}.${CHR}.f1r2.tar.gz "; done)

MutectCallDoneSignal="done(MutectCall_1_${TimeID})"
for CH in ${CH_List}
do
  if [ ${CH} != "1" ]
  then
    MutectCallDoneSignal=${MutectCallDoneSignal}" && done(MutectCall_${CH}_${TimeID})"
  fi
done

bsub -W 24:00 -q medium -n 4 -M 40G -R rusage[mem=40] -e ${StoreDir}/MergeVCF_err.log -o ${StoreDir}/MergeVCF_out.log \
     -w "${MutectCallDoneSignal}" \
     -J "MergeVCF_${TimeID}" \
     "${GATKver} MergeVcfs ${all_UnFilvcf} \
                         -O ${StoreDir}/merged.unfiltered.vcf"

bsub -W 24:00 -q medium -n 4 -M 40G -R rusage[mem=40] -e ${StoreDir}/MMS_err.log -o ${StoreDir}/MMS_out.log \
     -w "${MutectCallDoneSignal}" \
     -J "MMS_${TimeID}" \
     "${GATKver} MergeMutectStats ${all_UnFilvcfStats} \
                                -O ${StoreDir}/merged.stats"

bsub -W 24:00 -q medium -n 4 -M 40G -R rusage[mem=40] -e ${StoreDir}/LROM_err.log -o ${StoreDir}/LROM_out.log \
     -w "${MutectCallDoneSignal}" \
     -J "LROM_${TimeID}" \
     "${GATKver} LearnReadOrientationModel ${all_f1r2_input} \
                                         -O ${StoreDir}/read-orientation-model.tar.gz"

#bsub -W 24:00 -q medium -n 4 -M 120G -R rusage[mem=120] -e ${StoreDir}/${Tag}_GPS_CC_err.log -o ${StoreDir}/${Tag}_GPS_CC_out.log \
#     -J "GPS_CC_${Tag}_${TimeID}" \
#     "${GATKver} ${JavaOption} GetPileupSummaries -I ${BamPath} -V ${GnomadVCF} -L ${GnomadVCF} -O ${StoreDir}/getpileupsummaries.table && \
#      ${GATKver} ${JavaOption} CalculateContamination -I ${StoreDir}/getpileupsummaries.table -tumor-segmentation ${StoreDir}/segments.table -O ${StoreDir}/calculatecontamination.table"

FMC_CMD="${GATKver} ${JavaOption} FilterMutectCalls -R ${RefFa} \
                                  -V ${StoreDir}/merged.unfiltered.vcf \
                                  --ob-priors ${StoreDir}/read-orientation-model.tar.gz \
                                  --stats ${StoreDir}/merged.stats \
                                  -O ${StoreDir}/merged.filtered.vcf"

bsub -W 24:00 -q medium -n 4 -M 80G -R rusage[mem=80] -e ${StoreDir}/FMC_err.log -o ${StoreDir}/FMC_out.log \
     -w "done(MergeVCF_${TimeID}) && done(MMS_${TimeID}) && done(LROM_${TimeID})" \
     -J "FMC_${TimeID}" \
     "${FMC_CMD}"
#     "${GATKver} ${JavaOption} FilterMutectCalls -R ${RefFa} \
#                                               -V ${StoreDir}/${Tag}.merged.unfiltered.vcf \
#                                               --tumor-segmentation  ${StoreDir}/segments.table \
#                                               --contamination-table ${StoreDir}/calculatecontamination.table \
#                                               --ob-priors ${StoreDir}/${Tag}.read-orientation-model.tar.gz \
#                                               --stats ${StoreDir}/${Tag}.merged.stats \
#                                               -O ${StoreDir}/${Tag}.merged.filtered.vcf"

exit
